[package]
name = "walk"
version = "0.1.1"
authors = ["Seb Glazebrook <sebastian.glazebrook@redbubble.com>"]

[lib]
name = "walk"
path = "src/lib.rs"

[dependencies]

clap = { version = ">=2.11.2", features = ["yaml"] }
